server:
  port: 8989 # 端口号
spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/db/test.db # 创建的sqlite数据库所在路径
    username: # 因为没有用户名和密码，所以这两个参数就没有值
    password:
    driver-class-name: org.sqlite.JDBC # sqlite驱动

# mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml # 配置mapper.xml文件路径
  type-aliases-package: com.sei.tamias.db.entity # 实体类包名
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
# mybatis 打印SQL, 配置后就会在控制台打印执行的SQL语句
logging:
  level:
    com.sei.tamias.db.mapper: debug
